### ISSUE TITLE
Webpack not transipiling .js files correctly.

### ISSUE THREAD

**Issue by riavalon** [rangle/rangle-starter#106]
Webpack is not handling transpilation of .js configuration files, for example the shims/shims_for_IE.js .

This is causing the starter apps to break in IE9 when they encounter the `const` keyword.

**Comment by codebyuma** [comment]
@riavalon and I just discussed this bug. It was introduced when I added linting of config files and updated the shims file to abide by the new eslintrc rules (https://github.com/rangle/rangle-starter/issues/95). The starters work in IE11 but not IE9. 

There are a few options (my pick is excluding this specific file from linting and reverting it to ES5-friendly code) and @riavalon is going to investigate a bit more first.

**Comment by SethDavenport** [comment]
Cool thanks for the update

**Comment by SethDavenport** [comment]
@codebyuma @riavalon I think you two fixed this up already right?

**Comment by codebyuma** [comment]
Looks like it. @riavalon, can you confirm if this can be closed?
