### ISSUE TITLE
Investigate Codelyzer

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#108]
https://www.npmjs.com/package/codelyzer

Codelyzer provides extra lint rules from the Angular2 community.  We should take if for a spin, and if it's good, hook it up to our angular 2 starters.

**Comment by sumitarora** [comment]
@SethDavenport Implemented in Angular2 Started apart from prefixing rule rest looks good just need to decide on the rules to be followed by all angular projects. https://github.com/rangle/angular2-starter/pull/36
