### ISSUE TITLE
Add 'cover'-script to typescript-react-redux-starter package.json

### ISSUE THREAD

**Issue by aramin** [rangle/rangle-starter#112]
Currently the cover-task is missing in the package.json of https://github.com/rangle/typescript-react-redux-starter

**Comment by SethDavenport** [comment]
This is connected to rangle/rangle-starter#12

**Comment by clbond** [comment]
I implemented code coverage report generation for typescript-react-redux-starter in https://github.com/rangle/typescript-react-redux-starter/pull/169, but it does not use an "npm run cover" command, it just is part of the "npm run test" run / karma configuration - not a separate command.
