### ISSUE TITLE
ng2 - Super small filename typo

### ISSUE THREAD

**Issue by hyperwidget** [rangle/rangle-starter#118]
the test file at: src/components/container is named: 'index.text.ts' it should be named 'index.test.ts'

**Comment by JaKXz** [comment]
~~Looks like this has been taken care of,~~ but thanks for pointing it out @rawkamatic! Feel free to make PRs in future 😺

**Comment by JaKXz** [comment]
Sorry! I checked the [wrong repo](http://github.com/rangle/angular2-redux-starter/). PR made now though :)
