### ISSUE TITLE
Get TypeScript Code Coverage Working

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#12]
Currently not hooked up for at least the angular 2 starter - let's make sure it's hooked up for all starters.

**Comment by SethDavenport** [comment]
This is fixed in es6-react

**Comment by rudijs** [comment]
Hi,

+1 would love to see HTML code coverage reports.

This is the very first thing I went looking for:

1) git clone
2) npm i
3) npm test
4) find the HTML code coverage... not there? direct to issues and search for "coverage".

I'm going to spend a little time now looking at it locally, but from my Angular1 + webpack + karma/istanbul experience it can be a time sink to figure out and get going.

Cheers.

**Comment by SethDavenport** [comment]
We've been struggling to get istanbul to work properly with typescript.  If you have some thoughts around this I'd love to hear them.

**Comment by rudijs** [comment]
Yeah I know it's not so simple to get going.

I haven't had a look at this repo yet, but I have got it working with AngularJS v1.x.

The stack is:

Typescript
Mocha
Sinon
Chai
Karma
Instanbul
Webpack

There's some webpack pre-loader configs in karma.conf that did the trick for me.

You might like to take a peek at lines 7-25

https://github.com/rudijs/ng-docker/blob/master/karma.conf.js

You're welcome to clone that repo and give it a whirl - it should work out of the box.

```
git clone https://github.com/rudijs/ng-docker.git
npm i
npm test
```

Then view the reports in test/coverage.

I was playing around with Angular2 w/ Webpack around beta 3 but ran into some weirdness so haven't touched it again.

It's frustrating to blow time on, so I figured sitck with ng v1.x for now.

**Comment by SethDavenport** [comment]
@JaKXz : something fishy with the coverage in the angular2 starter:

``` sh
> angular2-redux-starter@0.2.0 cover /Users/sdavenpo/code/rangle/angular2-redux-starter
> remap-istanbul -i coverage/chrome/coverage-final.json -o coverage/coverage.json

[Error: Could not find source map for: "/Users/sdavenpo/code/rangle/angular2-redux-starter/src/utils/fire-action.ts"]
[Error: Could not find source map for: "/Users/sdavenpo/code/rangle/angular2-redux-starter/src/reducers/counter.ts"]
[Error: Could not find source map for: "/Users/sdavenpo/code/rangle/angular2-redux-starter/src/constants/index.ts"]
[Error: Could not find source map for: "/Users/sdavenpo/code/rangle/angular2-redux-starter/src/reducers/session.ts"]
[Error: Could not find source map for: "/Users/sdavenpo/code/rangle/angular2-redux-starter/src/utils/is-promise.ts"]

> angular2-redux-starter@0.2.0 postcover /Users/sdavenpo/code/rangle/angular2-redux-starter
> istanbul report lcov text-summary


=============================== Coverage summary ===============================
Statements   : 98% ( 49/50 )
Branches     : 92% ( 23/25 )
Functions    : 100% ( 6/6 )
Lines        : 97.67% ( 42/43 )
================================================================================
```

First the source map errors, second the fact that coverage should not actually be anywhere near that high yet. Looks like we're only instrumenting the files that have tests.

**Comment by JaKXz** [comment]
@SethDavenport the error about the sourcemaps is due to `remap-istanbul`, there are open PRs on that project that once merged and released might take care of it [which would help cover the real .ts files].

**Comment by SethDavenport** [comment]
Another random idea I had was to try and use ts 1.8's ability to dump the transpilation into a big file and then run that through karma sans webpack.

Might simplify some of the remap issues so it's worth a try.

**Comment by JaKXz** [comment]
That's a great idea. I'm going to unassign myself and move this back to ready since I've done as much digging into this as I can manage right now.

**Comment by clbond** [comment]
This is implemented/fixed in these PRs: https://github.com/rangle/angular-redux-starter/pull/135, https://github.com/rangle/angular2-redux-starter/pull/180, https://github.com/rangle/angular2-starter/pull/54. Moving to done
