### ISSUE TITLE
ts-react: Are String property lookups unavoidable?

### ISSUE THREAD

**Issue by mikecann** [rangle/rangle-starter#121]
Hi,

I was looking through the code and it all looks great and uses the type safety aspects of Typescript almost perfectly. The only issues I see are with immutable JS. 

For example: https://github.com/rangle/typescript-react-redux-starter/blob/master/src/reducers/session.test.ts 

```
 assert(!state.get('isLoading'));
 assert(!state.get('hasError'));
 assert(state.get('token') === 1234);
```

All those string based property lookups give me the heeby jeebies. Is there no way around them?

Cheers,
Mike

P.S. Not sure how to add a label to this so putting in the title instead.

**Comment by SethDavenport** [comment]
Hi @mikecann - actually our reducers in this project could probably stand stronger typing in general.

I started to do it in our angular2+redux starter here: https://github.com/rangle/angular2-redux-starter/blob/master/src/reducers/index.ts and here https://github.com/rangle/angular2-redux-starter/blob/master/src/reducers/session.ts

In that starter the session state slice has type `Immutable.Map<string, any>`. This sort of makes sense given that the strings are in fact property names, which are normally reasonable to model as strings.

On the one hand, we could model the session type explicitly, e.g.:

``` typescript
interface ISession {
 hasError: boolean,
 isLoading: boolean,
 token: string
};
```

and then simply access it as it were a regular JS object: `assert(!state.isLoading));`. While this provides stronger guarantees about the field types, we lose the guarantee of immutability provided by ImmutableJS.

We made the judgment call that the immutability guarantee was more important:  it stops people from accidentally making impure reducers or selectors (which would basically break the whole redux system).

I often find that heavily functional patterns like redux have an uneasy truce with strong typing. I try to use tools from both paradigms as effectively I can.

OTOH if there's a way to have our immutable cake and eat our typings too I'm all ears.

**Comment by mikecann** [comment]
Hi @SethDavenport,

> I often find that heavily functional patterns like redux have an uneasy truce with strong typing. I try to use tools from both paradigms as effectively I can.

I totally agree with you, I think that may be the core reason I am having troubles with my current workflow.

I understand the need to immutability and sadly it breaks my strongly-typed urges :smile: 

Cheers,
Mike
