### ISSUE TITLE
Angular2: 'Npm run dev' refreshing from dist instead of memory?

### ISSUE THREAD

**Issue by sachasayan** [rangle/rangle-starter#123]
When making an edit on a project based on the Angular2-Redux starter, running an `npm run dev` server and then editing a file seems to result in inconsistent/broken refreshes — it appears that we're trying to refresh from dist instead of memory. 

Steps to reproduce: 
1. Clone the `angular2-redux` starter. 
2. `npm run dev`
3. Make an edit, template or otherwise. 
4. Watch as your edit doesn't appear in the browser... UNLESS you explicitly load the page from the URL bar. (Refreshing of any kind doesn't seem to work..)

(Could this be related to #122?)

**Comment by SethDavenport** [comment]
@ssayan what port do you have in your browser location bar?

**Comment by SethDavenport** [comment]
Should be 8080

**Comment by BrendanFDMoore** [comment]
In order to simulate real http auth requests, `npm run dev` actually
results in two servers running. The front end client should be accessed
from port 8080 as @sethdavenport suggests. On port 3000 is another server
supplying the api for authenticating credentials. This has a byproduct effect
of offering the client up a second time.

We could probably stand to clear this up some.

**Comment by codebyuma** [comment]
May need to add webpack hot reload? I think Mark was looking at that.

**Comment by sachasayan** [comment]
@SethDavenport @BrendanFDMoore To be clear, this _was_ encountered accessing the front-end client via 8080.

**Comment by stevenkampen** [comment]
@SethDavenport @BrendanFDMoore @ssayan I ran into this also, but I worked around it by hijacking `node-proxy.js` to redirect all requests back to the root of `localhost:8080`. This breaks the fallback `/dist` serving, so I was thinking maybe it should be applied separate to the proxy config logic, and only if it's not in production mode (i.e. `npm run dev` was run)?

In `proxy-config.js`...

```
module.exports = {
  // Calls to /api/foo will get routed to
  // http://jsonplaceholder.typicode.com/foo.
  /*
  '/api/': {
    target: 'http://jsonplaceholder.typicode.com',
    changeOrigin: true,
  },
  */
  '/': {
    target: 'http://localhost:8080',
    ignorePath: true,
  },
};
```

**Comment by SethDavenport** [comment]
This was introduced when we added an API call to the node server to demonstrate HTTP requests.

Making webpack proxy \* screws up app reloading dev server. However we only need to proxy api/\* (plus whatever manual configs are in the proxy settings for remote APIs).

@mdegani already submitted a fix for this; I finally had time to review and merge it.

**Comment by SethDavenport** [comment]
I'll port it over to the other starters.
