### ISSUE TITLE
Webpack Broken on Windows Due To `SplitByPath`

### ISSUE THREAD

**Issue by bennett000** [rangle/rangle-starter#128]
Unfortunately SplitByPath has an issue with regex and Windows paths: https://github.com/BohdanTkachenko/webpack-split-by-path/issues/12

The good news is there's a PR that might fix this: https://github.com/BohdanTkachenko/webpack-split-by-path/pull/14

The bad news is the PR has been up since April.  I pinged the maintainer, hopefully it can get merged or fixed some other way.

**Comment by SethDavenport** [comment]
Blerg.  Thanks for filing the issue.

I guess we can go back to CommonsChunkPlugin, but it's more config to maintain.

**Comment by bennett000** [comment]
It's pretty painful having to switch to more config because of a regex error.

**Comment by bennett000** [comment]
Great news, the PR got merged, things should work again: https://github.com/BohdanTkachenko/webpack-split-by-path/pull/14#issuecomment-225001163

I'm assuming Green Keeper will take care of this.  I will close the issue.
