### ISSUE TITLE
CI should fail on tslint, scsslint errors

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#13]

**Comment by SethDavenport** [comment]
Webpack-dev-server will show you tslint errors, but the CI command (npm test) will still pass.

**Comment by SethDavenport** [comment]
This is an old issue moved over from the angular starter repo; might just need validating.

**Comment by SethDavenport** [comment]
Validated that this is set up for react-redux-starter.  However it's not set up for typescript-react-redux-starter.  One complication is that `tslint` doesn't support folders as arguments like `eslint` does.  Specifying all our files one by one is impractical.

Let's keep an eye on this PR: https://github.com/palantir/tslint/pull/857

**Comment by SethDavenport** [comment]
An alternative would be to configure webpack tslint-loader to fail on warnings as part of `npm build`; I don't really like the way this mixes concerns though.

**Comment by louy** [comment]
it supports globs though. `tslint 'dir/**/*.ts'`

**Comment by SethDavenport** [comment]
es6-react verified: `npm test` runs `eslint` correctly.

**Comment by SethDavenport** [comment]
@louy: thanks - I tried a similar glob but was missing the quotes. Seems to work with them.

**Comment by SethDavenport** [comment]
submitted PR for ng1

**Comment by SethDavenport** [comment]
submitted PR for ng2

**Comment by SethDavenport** [comment]
submitted PR for ts-react
