### ISSUE TITLE
angular2-rc3 is out last week - no support

### ISSUE THREAD

**Issue by nasreddineskandrani** [rangle/rangle-starter#133]
when you will upgrade to rc3 support please?

**Comment by SethDavenport** [comment]
Duplicate of #132

**Comment by SethDavenport** [comment]
We're still evaluating the router situation - there's no router-deprecated in RC3, but the v2 and v3 routers are still experimental.

**Comment by SethDavenport** [comment]
angular2-starter and angular2-redux-starter have been updated to RC3.
