### ISSUE TITLE
Update angular starter to router v3

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#136]
This PR might be helpful: https://github.com/rangle/ngCourse2/pull/270/files

For the redux starter, let's make see if we can ensure the implementation is properly reactive - e.g. rewinding in redux dev tools should rewind route changes as well.

**Comment by SethDavenport** [comment]
Might want to wait until it's out of alpha though.

**Comment by danielmhair** [comment]
Any update on this? I'm trying to keep up with the latest version of Angular 2. I'm uncertain whether I should remain with `router-deprecated` with this repo had it when I cloned it or try to use router v3 on my own.

**Comment by SethDavenport** [comment]
Working on it - #147.  angular2-starter should be good to go.

Still need to iron out some peer dependency fun with RC4 for the angular2-redux-starter.
