### ISSUE TITLE
Harmonize react and angular unit tests toolchains

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#139]
The angular setups with Karma and instanbul are finally working well, thanks to @clbond.

Let's get that goodness into react-redux-starter and typescript-react-redux-starter

**Comment by clbond** [comment]
This is implemented in these PRs:

react-redux-starter - https://github.com/rangle/react-redux-starter/pull/217
typescript-react-redux-starter - https://github.com/rangle/typescript-react-redux-starter/pull/169
