### ISSUE TITLE
Window `npm run X` failures: possible ' vs " issue

### ISSUE THREAD

**Issue by bennett000** [rangle/rangle-starter#148]
Some commands have been failing on windows, notably:
- CSS lint
- Commands using concurrently

Manifestation for the CSS lint issue is that no files are found it's like it does not see the arguments

Manifestation for the concurrently issue is an error than says something _like_ `command np is not a command`

One _unconfirmed_ solution was to avoid `'` quotes in `package.json` `scripts`

**Comment by SethDavenport** [comment]
Reopening - this needs to be checked on all starters. Remaining: react-starter, angular1-starter, angular2-starter, api-koa-starter

**Comment by bennett000** [comment]
Talk to me about a Windows box for this whomever picks it up.

- [ ] The sample apps should also be made windows compliant
