### ISSUE TITLE
Production error in console

### ISSUE THREAD

**Issue by rbrander** [rangle/rangle-starter#15]
On heroku, the following error is happening in the console:

You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production 

This started happening due to a change in redux v3.0.6: https://github.com/rackt/redux/releases/tag/v3.0.6

The solution is to modify the webpack.config.js:

  new webpack.DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
  }),

**Comment by SethDavenport** [comment]
Ng1: https://github.com/rangle/angular-redux-starter/pull/26

**Comment by SethDavenport** [comment]
Ng2: https://github.com/rangle/angular2-redux-starter/pull/30

**Comment by SethDavenport** [comment]
ES6-React: https://github.com/rangle/react-redux-starter/pull/68

**Comment by SethDavenport** [comment]
TS-React: https://github.com/rangle/typescript-react-redux-starter/pull/15

**Comment by SethDavenport** [comment]
Fixed in all starters.
