### ISSUE TITLE
Decouple example apps from starters?

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#152]
These starters have two purposes: 

1) to give our projects a toolchain setup, and
2) to serve as architectural examples.

However recent experience suggests that 2 is interfering with 1 somewhat. It would be nice to separate the two concerns.

How do we do this without going nuts trying to keep 10 things up-to-date?

**Comment by SethDavenport** [comment]
One suggestion would be to keep two versions of the sample app: NG2+Typescript and React+Babel (down from four), put them in their own repos, and not worry too much about keeping the up to date with package updates.

The starter projects would then just be a hello world page and toolchain stuff, but kept aggressively up-to-date.

Projects get their starter kits, and when people want code examples we can just point them to the two sample apps above.

**Comment by SethDavenport** [comment]
Another proposal is to make the rangle-starter CLI strip out the sample app when you use it to clone.

**Comment by SethDavenport** [comment]
Discussion welcome.

**Comment by RSNara** [comment]
> Another proposal is to make the rangle-starter CLI strip out the sample app when you use it to clone.

Not too sure if this is the easiest solution. We already have a handful of starters, all of which don't look to be configured in exactly the same fashion. Adding all that logic to strip out the sample app into the cli seems like it could be a pain to implement and maintain. Also, it'd introduce coupling between the starters and the `rangle-starter` cli, which would make upgrading the starters with their examples more difficult.

> One suggestion would be to keep two versions of the sample app: NG2+Typescript and React+Babel (down from four), put them in their own repos, and not worry too much about keeping the up to date with package updates.

Speaking from personal experience, I think this might be a good idea. Whenever I start a new project by cloning the starters, I almost always do it because I need to toolchain, not the examples. It's often the case that I end up deleting everything and migrating only the things I need form the starter. I think the experience is not unlike buying a new computer and having to manually uninstall the copious amount of bloatware that come with it.

It seems to me like the example code provides more value in repository that serves as a reference for good practices and designs. That way, maintaining the starters becomes easy for us, and using the starters may become easier for rangle developers that eventually use them. But yeah, I've largely just used the starters for experimentation, side projects, and only **one** Rangle project. It would actually be pretty cool to see what existing teams (who started their projects with the starter) think about this.

**Comment by danielmhair** [comment]
I vote for the latter:

> One suggestion would be to keep two versions of the sample app: NG2+Typescript and React+Babel (down from four), put them in their own repos, and not worry too much about keeping the up to date with package updates.

**Comment by SethDavenport** [comment]
Right now we have 6 starter repos:
- Ng1 + TS + Redux
- Ng2 + TS + Redux
- Ng2 + TS
- React + TS
- React + Babel
- Koa + Babel

Each one (except Koa) contains a starter app. Splitting them as-is would result in 11 repos, which I don't have time to maintain :)

Ng2 + TS only exists because some people found the Ng2 + TS + Redux starter complicated as a starter.

Here's what I propose: we split the example apps and the starters up as follows:

*\* Starters **
Ng1 + TS
Ng2 + TS
React + TS
React + ES6
Koa

The starters would be kept up to date with toolchain fixes.

*\* Sample Apps **
Redux app with Ng2 + TS
Redux app with React + ES6
Redux app with Ng1 + TS

The sample apps would be more static; probably I'd turn off greenkeeper for them and simply use them as reference material for internal and external training.

This only adds 2 new repos to the total number (8), of which 5 would be maintained aggressively.

Given that ng1 is not a huge priority right now we could probably just deprecate, it if necessary.

Thoughts?

**Comment by e-schultz** [comment]
Overall I think this is a good idea, looking at projects that have used the starter - the first commits are always renaming things and/or dropping things. Getting them to be a bit more minimal/barebones would be good. 
- create new repo, angular2-starter-example -> current angular2-starter 
- angualr2-starter -> rip out 'app' part, down to a hello-world 
- new angular2-starter-redux-example -> current  angular2-redux-starter 
- angular2-redux-starter -> drop/deprecate repo, point to angular2-starter-redux-example

**Comment by SethDavenport** [comment]
@e-schultz let's not have 'starter' in the example repos

also I don't think we need two angular2 examples (with and without redux). Let's just have the redux one.

**Comment by e-schultz** [comment]
ok, so
- angular2-starter-example -> kill
- angular2-redux-starter -> angular2-redux-example 
- angular2-starter -> update readme to point to the example, and merge the PR removing the sample app

**Comment by SethDavenport** [comment]
Per the support squad meeting today, it sounds like we're in agreement about the starters being decoupled from the examples.

Here's the wishlist we came up with for what a starter should do:
- `npm run build` -> bundle and package statically
- `npm run dev` -> run dev mode with watching, live & hot reload as applicable, debuggable
- `npm test` -> run linters, unit tests, and coverage report
- `npm test:watch` -> TDD mode unit tests
- Proper CSS toolchain (@winkerVSBecks - include basscss by default or not?)
- Basic config for Heroku

With this in mind we would need the following starters for now:
- ES6 + base react/css libs (react-starter)
- TS + base angular2/css libs (angular2-starter)
- TS + base angular1/css libs (angular-starter)
- ES6 + Koa (api-koa-starter)

**Comment by SethDavenport** [comment]
We should make a similar wishlist for example repos. Ideally we'd want a minimal set that covers the following:
- how to do redux with typescript
- how to do redux with babel
- how to do components with React
- how to do components with Angular 2
- how to do e2e tests with robot
- how to do selectors with ng2-redux (`@select`)
- how to do selectors with react (reselect)
- how to to side-effects with ng2-redux (Epics?)
- how to do side-effects with react (sagas?)

**Note that I'm not suggesting an example for each of these!**

We can probably come up with two or three examples that cover all the bases.

Also note that our TS-React starter is decently popular, probably because few other people are doing it. So even if we decide to not maintain it any more we should probably keep it around somewhere.

**Comment by SethDavenport** [comment]
Where possible we should rename existing repos to be the examples and spin up new ones for the starters

So links that have been sent out/stars for the more popular examples are retained.

## Examples:

Currently I'm thinking the following set of examples will cover the bases above. Where possible we should rename existing starters into the new examples because there are a lot of links to them in the wild (blog posts, gitter, slides, etc.)

### Official Examples (maintained as we come up with better ideas; keeping deps up to date less important)

react-redux-starter: rename to react-redux-example
- ES6/Babel
- Redux
- React
- Sagas? (to be implemented)
- turn off greenkeeper

angular2-redux-starter: rename to angular2-redux-example
- Typescript/Babel
- Redux
- Angular2
- Epics
- Typed Immutable Record?
- turn off greenkeeper

## Best-effort, but unofficial examples (kept around due to community interest but no longer actively maintained)

typescript-redux-starter: rename to typescript-react-redux-example
- not make any real changes - just keeping it around because it has lots of community stars
- turn off greenkeeper

angular-redux-starter: rename to angular1-redux-example
- deprecated; just keeping it around for the odd project that still uses ng1 and as a potential source of migration knowhow (ng1+typescript+components)
- turn off greenkeeper

## Gutted, toolchain only starters

Aggressively maintained but no app code beyond a 'hello world' page.
- ES6 + base react/css libs (react-starter)
- TS + base angular2/css libs (angular2-starter)
- ES6 + Koa (api-koa-starter)

@josepot @e-schultz does this sound good? If so I think @josepot has some cycles.

**Comment by SethDavenport** [comment]
Retired angular2-redux-starter as above. The old repo is still available as https://github.com/rangle/angular2-redux-example - there are a few cleanup items on that repos issues page for anyone who's interested.

**Comment by bennett000** [comment]
@watrool was able to setup the dedicated react starter at: https://github.com/rangle/react-starter

It still contains Redux and the Router and the rest of the tool chain as well as the utils, but no app code.

**Comment by bennett000** [comment]
react-redux-starter renamed to react-redux-example.  The old link still works :)
- https://github.com/rangle/react-redux-starter
- https://github.com/rangle/react-redux-example

React/TS also updated:
- https://github.com/rangle/typescript-react-redux-starter
- https://github.com/rangle/typescript-react-redux-example

**Comment by SethDavenport** [comment]
A few more action items for this story:
- split the angular1-redux-starter into a minimal angular1-starter and an angular1-redux-example like we did for the others.
- remove `React with TypeScript and Redux` and an option from the rangle-starter command line (and from the README).
- turn off greenkeeper for the examples.
- nuke the other angular2 example if @e-shultz is OK with it (repo name angular2-starter-example)

**Comment by troyt-42** [comment]
@SethDavenport @bennett000 Can we close this issue? It seems all the starters have been separated from examples.

**Comment by SethDavenport** [comment]
@bennett000 @watrool looks like angular-redux-starter still needs to be split.

**Comment by SethDavenport** [comment]
Consensus is that it makes sense to keep the angular1 example as is for now.
