### ISSUE TITLE
angular2-redux-starter vs heroku

### ISSUE THREAD

**Issue by nasreddineskandrani** [rangle/rangle-starter#154]
i tried to use with heroku this repo: 
https://github.com/rangle/angular2-redux-starter

Not working for me. Can someone tell me if he get it working with heroku? 

I was working without the server code. I was using locally `npm run dev:client` to run my ng2 client.
now i think we can't rely in webpack server on heroku so i let the default npm start in the Procfile that start nodeserver but not working. He complain about postinstall script (typing...)

well checking this issue i think its working for you: 
https://github.com/rangle/rangle-starter/issues/125

i ll retry tomorow or on weekend with the project as is without my change. Will let you know the state.

**Comment by SethDavenport** [comment]
This repo's master branch auto deploys to a heroku instance: http://angular2-redux-starter.herokuapp.com/counter

It runs `npm start` which is the command to start the sample app in release mode (without webpack-dev-server).

However by default Heroku doesn't install the dev dependencies; you need to set NPM_CONFIG_PRODUCTION = false in Heroku's config section. Can you give that a try?

**Comment by nasreddineskandrani** [comment]
it's working thank you.
