### ISSUE TITLE
angular2-starter production build fails

### ISSUE THREAD

**Issue by e-schultz** [rangle/rangle-starter#155]
Get error:
<img width="548" alt="screen shot 2016-07-27 at 11 58 59 am" src="https://cloud.githubusercontent.com/assets/3045906/17182451/8b2b92e8-53f1-11e6-89b0-ef45aa0f8a7d.png">

If I remove the `new webpack.optimize.OccurenceOrderPlugin()` from the webpack plugins, it works though.

**Comment by SethDavenport** [comment]
Hmm - it's working for me...
