### ISSUE TITLE
Prune dependencies

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#166]
The angular2-starter has a bunch of dependencies left over that are no longer needed.  For example,  since the app exists, we don't need the whole server folder and can drastically simplify the toolchain.

**Comment by SethDavenport** [comment]
- delete the /server folder
- remove all the server side deps from package.json
- update the scripts in package.json to just run webpack-dev-server in dev mode 
- update the scripts in package.json to just serve the contents of dist in prod mode (npm run dev) using a baked in http server like `http-server` from npm.

**Comment by troyt-42** [comment]
`SplitByPathPlugin` was causing problem when use `http-server` to serve ./dist:

<img width="1320" alt="error" src="https://cloud.githubusercontent.com/assets/7275468/18316008/09d2aad0-74e7-11e6-91ae-ba9a237ad41c.png">

**Comment by SethDavenport** [comment]
The issue with commenting it out is that now all the code goes into one big bundle instead of an app.js and a vendor.js.

Since vendor code in a project changes less often, we want to be able to cache it separately.

Now that you mention it though I think @bennett000  ran into issues with webpack 2 and splitbypath - so we changed over that project to CommonsChunk plugin instead.

**Comment by bennett000** [comment]
@SethDavenport yes I did run into split by path with Webpack 2.  I think others ran into that too.  The chunks plugin works although it's more tedious.  That said I **think** tree shaking enforces a _singluar_ bundle (no vendor)
