### ISSUE TITLE
Revaluate Shims-for-IE

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#167]
Take a look at the 'shims/shims-for-ie.ts' file. This is something I added for ng2 beta where their support for IE9 was broken out of the box.

Since then, they've improved their polyfills. Let's see if we can get rid of some or all of this file with RC6.

**Comment by troyt-42** [comment]
I tried the app on IE 9.0.8112.16421 and it seems that simply removing shims_for_IE.ts is fine.

**Comment by SethDavenport** [comment]
Great - can you go ahead and do that?

**Comment by troyt-42** [comment]
Yes, I just created a PR: https://github.com/rangle/angular2-starter/pull/146
