### ISSUE TITLE
Get AoT working

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#168]
The Angular offline Template compiler (AoT) is supposed to drastically reduce bundle size in prod mode.

It relies on webpack 2, ts 2, and some changes to the way we transpile import statements.

Let's see if we can get it working in the ng2-starter.

David baretto or Eric Jimenez can likely help point you in the right direction.

**Comment by gillianml** [comment]
Currently blocked by Google team. See comments in PR
