### ISSUE TITLE
Get proper code coverage reporting set up

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#169]

**Comment by SethDavenport** [comment]
I noticed the other day that the angular2 starter has text-only coverage reports for unit tests. It is also possible to set up html reports that you can open in your browser; these reports let you drill down to the parts of the code that aren't well covered.

I believe we have gotten this working in the angular2-redux-example app; while that's an older toolchain it might help you set it up for angular2-starter.  Just run `npm test` on the example app and open the `coverage` folder that gets generated.

Alternately it might be worth checking out the webpack version of angular-cli (`npm install -g angular-cli@1.0.0-beta.11-webpack.8`) to see what it generates.

**Comment by clbond** [comment]
Resolved by https://github.com/rangle/angular2-redux-example/pull/275

**Comment by clbond** [comment]
Resolved by https://github.com/rangle/angular2-redux-example/pull/275

**Comment by bennett000** [comment]
The main Angular 2 starter's karma specifies HTML reporting too so I'm moving this card to done
