### ISSUE TITLE
Harmonize react and angular 2 sample apps

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#17]
Probably base things on the react apps, since they're more mature.

**Comment by SethDavenport** [comment]
Alan has volunteered to take a look at this.

**Comment by alanthai** [comment]
@SethDavenport

Two questions:
1) Do you want things broken down into bite-sized components like in React (including feeding in inline styles, etc)
2) Is [Angular2 Forms](https://angular.io/docs/ts/latest/guide/forms.html) the best way to handle forms? (I don't know of any redux-form alternatives)

**Comment by SethDavenport** [comment]
1) Yes - I would like to keep the same folder and component structure across apps as much as possible.  In general granular components and inline styles are the way we're going.

For the angular2 components, try to stick to basscss the way it's done in React, but for any 'inline' stuff, you can aways use 

``` typescript
@Component({
style: [`
  .foo { ... }
`]
})
```

... which angular 2 cleverly scopes to the component by default.

2) I would ask @e-schultz or @tyllrb what the current thinking on Ng2 forms is and do that.

**Comment by SethDavenport** [comment]
@mattmcfad @alanthai I would also suggest making one or two components: maybe say the about page first and put that up for code review.  Then we can sync up on approach before getting in it too deep.

**Comment by mattmcfad** [comment]
@SethDavenport sounds good :+1:

**Comment by e-schultz** [comment]
@SethDavenport @alanthai Still playing around with forms in Angular 2, trying to get a feel of going with purely template-driven forms vs using the form builder.

While I do think that there can be benefit to keeping your form state in a reducer, especially from a debuggability perspective - I think it's more of a 'nice to have', not a 'must have', unless a feature request actually required it (ie: auto-save, undo/history, or some other aspect of your application depended on what is in the form before it's in a completed state).

As a first pass at this, having it so form state isn't in application state, but just the final submit/whatever action fires off the action creator to dispatch the action with the form data is fine.
