### ISSUE TITLE
Uncaught Error: Zone already loaded. [ng2]

### ISSUE THREAD

**Issue by jphustman** [rangle/rangle-starter#170]
When running 'npm run dev' the application will not start, Chrome debugger says:

```
Uncaught Error: Zone already loaded.       localhost/:5
```

**Comment by sonukapoor** [comment]
@jphustman Remove the Zones.js from the webpack.config.js in the vendors array. Make sure to keep the last comma after immutable. Your vendor array should look like this:

```
vendor: [
      '@angular/core',
      '@angular/compiler',
      '@angular/common',
      '@angular/http',
      '@angular/platform-browser',
      '@angular/platform-browser-dynamic',
      '@angular/router',
      'core-js',
      'rxjs',
      'immutable',
    ]
```

**Comment by jphustman** [comment]
Great thank you, that is how i worked around it, but wasn't sure enough to create a pull request, I'm still trying to wrap my head around webpack.
