### ISSUE TITLE
Big vendor file

### ISSUE THREAD

**Issue by srfoster** [rangle/rangle-starter#172]
I've been using this stack:

https://github.com/rangle/typescript-react-redux-starter

It's great.  

Now, I am trying to deploy a first production release and I'm noticing that my vendor file is massive (>2M).  Even when I freshly clone the above starter and run "npm install" I notice that the vendor.js file in dist/ is >400K, which still seems pretty big.

Is this expected?  Am I building something wrong?  Any tips on keeping my vendor file smaller?  My initial page load time is over 20 seconds. :(

**Comment by SethDavenport** [comment]
Hi @srfoster 

No that's definitely not expected!

When I make a prod build (`npm run build`) on that starter I get the following:

```
                             Asset       Size  Chunks             Chunk Names
    vendor.e18e30105d7e57d8b3a2.js     420 kB       0  [emitted]  vendor
      main.e18e30105d7e57d8b3a2.js    50.5 kB       1  [emitted]  main
vendor.e18e30105d7e57d8b3a2.js.map    3.74 MB       0  [emitted]  vendor
  main.e18e30105d7e57d8b3a2.js.map     168 kB       1  [emitted]  main
                        index.html  498 bytes          [emitted]
          assets/rangleio-logo.svg    3.46 kB          [emitted]
```

Can you check that your command has `NODE_ENV` set to `production`? (should be set up as part of the npm build script.

The other thing to check is the 'devtool' setting in `webpack.conf.js`: it should not be using 'inline-source-maps' in prod mode.

**Comment by srfoster** [comment]
Actually, `npm run build` works great.  Much smaller.  I was using `npm install`, which was producing the larger dist files.

Thanks for the help!

UPDATE: I was mistaken about this.  See below.

**Comment by srfoster** [comment]
Sorry to completely pivot what I just said, but I was mistaken.  I thought my build had gotten smaller, but I was looking at the base project's build:

https://github.com/rangle/typescript-react-redux-starter

In reality, neither my vender file nor the one from the base build has gotten smaller.  And `npm install` seems to produce the same stuff as `npm run build`.

Indeed, from what you posted above, I suppose I should assume that ~400Kb is normal for the base build?  So my own project's vendor file can only go up from there?

**Comment by SethDavenport** [comment]
Yes I'ma afraid so.

If there are some deps that you're not actually using you could try pruning them out. Might be able to drop some of the Basscss addons.

Another alternative is to upgrade to webpack 2 and see if tree shaking helps.

**Comment by srfoster** [comment]
Okay, that's fine.  Thanks for confirming.

**Comment by rbrander** [comment]
It appears this issue has been resolved; closing.
