### ISSUE TITLE
Detach global styles from root component

### ISSUE THREAD

**Issue by smithad15** [rangle/rangle-starter#181]
For `angular2-starter` we should use webpack to load our global styles into the `<head>` tag. With the current setup, if you include markup outside of your angular app you will have a flash of unstyled content until Angular bootstraps itself. Also, if you actually wanted to scope certain styles to your root component you are currently unable to do so.

**Comment by SethDavenport** [comment]
AoT doesn't support this unfortunately. So no dice I'm afraid.
