### ISSUE TITLE
CLI does not init a git repo if not connected to a GitHub repo

### ISSUE THREAD

**Issue by smithad15** [rangle/rangle-starter#186]
If you choose to not associate a GitHub repo with a new `rangle-starter` project during the setup process, it will not initialize the project with git. Should probably run a local `git init` on the project as if you had specified a GitHub repo, but leave the association of a `git remote` up to the developer.

**Comment by SethDavenport** [comment]
I think this is the desired behaviour - what if you're using hg ;)
