### ISSUE TITLE
Investigate Typescript Fork Checker

### ISSUE THREAD

**Issue by smithad15** [rangle/rangle-starter#192]
`awersome-typescript-loader` has the ability to fork the type-checking process for faster builds. Investigate adding this functionality for angular2-starter development builds

**Comment by SethDavenport** [comment]
Also investigate for ng1 starter.

**Comment by SethDavenport** [comment]
Try it, measure speed increase, decide if it's worth it.

**Comment by troyt-42** [comment]
I tried this with angular2-starter, and the `dev` mode is improved like 1s faster (which can be in accurate since my measure is very simple). But considering turning on fork checker is very easy,  we may want to have it on starters.
