### ISSUE TITLE
rangle/typescript-react-redux-example typings depressed

### ISSUE THREAD

**Issue by bullyork** [rangle/rangle-starter#212]
git clone git@github.com:rangle/typescript-react-redux-example.git
npm install

The error come - 'Error: Debug Failure. False expression: File  has unknown extension'.
when checked, it occours after 'npm run postinstall'

**Comment by brianzinn** [comment]
Same for me.  With a git clone and no other changes.

npm run test
```
28 12 2016 13:44:57.447:ERROR [karma]: Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (C:\GitHub\typescript-react-redux-example\node_modules\typescript\lib\typescript.js:3177:23)
    at Object.fail (C:\GitHub\typescript-react-redux-example\node_modules\typescript\lib\typescript.js:3182:19)
    at Object.extensionFromPath (C:\GitHub\typescript-react-redux-example\node_modules\typescript\lib\typescript.js:3324:15)
```

npm run dev:
```
[nodemon] starting `node server/node-server.js`
info: Listening on port 3000

Error: ENOENT: no such file or directory, stat 'C:\GitHub\typescript-react-redux-example\dist\index.html'
```

npm start and visiting localhost:8080 has same result as above.

Node: 7.2.1
npm: 4.0.5
tsc: 2.1.4
os: windows 10

**Comment by Kobold** [comment]
I believe this is due to a bug in tsc 2.1.4. Other discussions:

- https://github.com/Microsoft/TypeScript/issues/12749
- https://github.com/Microsoft/TypeScript/issues/13004

**Comment by SethDavenport** [comment]
I have pinned TS to 2.0.10 and this appears to be working again. Will check the next TS release when it happens.

**Comment by nh2** [comment]
Typescript 2.1.5 is now released.

**Comment by PhilipDavis** [comment]
FYI, according to this: https://github.com/Microsoft/TypeScript/issues/13256#issuecomment-270764790 the issue is in awesome-typescript-loader. Looks like you're using 1.0.0. Apparently, upgrading to 3.0.0 (which also requires upgrading Webpack to v2), eliminates the problem.
