### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.  - configuration.module.rules[11] should be an object.

### ISSUE THREAD

**Issue by spwizard** [rangle/rangle-starter#218]
When running npm install, the post build returns the above error.  I have tried upgrading to webpack 2.2 as I noticed a pull request for this, but it still fails.

**Comment by rbrander** [comment]
@spwizard Could you please provide reproduction steps?  Specifically, it would be good to know which type of starter you used.  It might also be helpful to post the error messages you are receiving, or the npm-debug.log file.

**Comment by SethDavenport** [comment]
Pretty sure this is no longer happening.
