### ISSUE TITLE
npm run dev - tooks about 6 seconds on reload

### ISSUE THREAD

**Issue by paceto256** [rangle/rangle-starter#219]
[typescript-react-redux-example]
When I run the app in dev mode it tooks about 6 seconds to rebuild.
While iterating a 100 times a day it's pain. Any suggestions how we can optimize it?

**Comment by rbrander** [comment]
@paceto256  The typescript-react-redux-example repo is no longer being used as part of the rangle-starter.  It has been replaced by an ES6 React/Redux starter.  Please create a new issue if you are still having issues in dev mode using the new React starter.
