### ISSUE TITLE
windows using rangle-starter

### ISSUE THREAD

**Issue by HansS** [rangle/rangle-starter#25]
run: npm install
        webpack

and get the following errors:¨

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2/bundles/angular2-polyfills' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2/bootstrap' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2/platform/browser' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2/platform/common_dom' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2/core' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2/router' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2/http' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'redux' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'redux-thunk' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'ng2-redux' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'redux-logger' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
 @ multi vendor

ERROR in Entry module not found: Error: Cannot resolve module 'ts' in C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

Hans@HP-HANS C:\Users\Hans\Web\js\angular20-redux\angular2-redux-starter

**Comment by SethDavenport** [comment]
HI @HansS , can you let me know what version of node and npm you are using?

**Comment by HansS** [comment]
Hi Seth,node: 5.3.0npm: 3.5.3
regardsHans

Date: Tue, 2 Feb 2016 06:58:57 -0800

**Comment by SethDavenport** [comment]
Thanks - currently I've tested it on Mac OS X (Yosemite, El Capitan) and Linux Mint 17.3.

We haven't needed to use this on Windows yet so there's likely some compatibility work that needs to be done.  I'll see if I can get someone here to look into it more.

**Comment by SethDavenport** [comment]
As discussed, @igor-ka can you take a look?

**Comment by SethDavenport** [comment]
It's also worth noting that the bootstrap script (`npm install -g rangle-starter`) probably also doesn't work on windows since it's a simple wrapper around a bash script.  We can probably look at that in a second pass though.

**Comment by igor-ka** [comment]
@SethDavenport I'll have a look whenever I get a chance :) but should be able to get Windows to work with minimal changes

**Comment by HansS** [comment]
Hi Seth,
thank's a lot that you also care for the windows version!
regardsHans

Date: Tue, 2 Feb 2016 12:05:43 -0800

**Comment by SethDavenport** [comment]
@HansS: angular2-redux-starter should work in Windows now.  To run it, do:

``` sh
git clone git@github.com:rangle/angular2-redux-starter.git
cd angular2-redux-starter
npm install
npm start # for prod mode, or 'npm run dev' for debug mode.
```
