### ISSUE TITLE
rangle-starter doesn't work on Windows

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#28]

**Comment by SethDavenport** [comment]
Because it's a simple wrapper around a bash script.

Might be able to get some traction with https://github.com/shelljs/shelljs

**Comment by bennett000** [comment]
Would migrating away from a simple script make this harder to maintain, and/or more prone to breaking?

ShellJS might be a good solution though, I haven't looked at it closely yet.

I _do_ know that it's not that complex to use a child_process wrapper, but how that fits with git on Windows I don't know.

**Comment by xorgy** [comment]
There are also bash distributions for Windows, which you are likely to require anyway.

**Comment by joeyrobert** [comment]
Thoughts on porting it to JS entirely? Minimal dependencies.

**Comment by xorgy** [comment]
@joeyrobert Considering that there's an entire node module just to implement "rm -rf", it would seem like overkill.

**Comment by joeyrobert** [comment]
The alternative is "implement a bash interpreter for Windows", which seems like a bigger overkill than using cross platform do-one-job libraries.

**Comment by xorgy** [comment]
Not `implement a bash interpreter for Windows`. There are bash binaries for Windows, just need to use them.

**Comment by joeyrobert** [comment]
Shell.JS seems like a decent compromise, but the functionality needed for this small script is built into node already (`fs`, child process).

**Comment by xorgy** [comment]
I'm specifically talking about [line 27](https://github.com/rangle/rangle-starter/blob/master/repocopy.sh#L27), which does an `rm -rf`.

There is no built-in support for recursive directory deletes in node, so people make modules like https://github.com/isaacs/rimraf to do it.

**Comment by SethDavenport** [comment]
The project already depends on rimraf for other reasons so that's not an issue as far as I know.

I've used a couple of bash binaries for windows, they were both kind of meh - cygwin, git-bash.

The script itself isn't that complicated.  The weirdest thing is does is apply some regexes, which is easy in JS.  Might be able to do it in vanilla JS.

**Comment by SethDavenport** [comment]
@bennett000 took a stab at porting to JS, needs cleanup and testing:

``` javascript
​
/*global process, require*/​
var spawn = require('child_process').spawn;
var path = require('path');
var rimraf = require('rimraf').sync;
​
var rxRepo = /[:\/](.+)\/(.+)\.git$/;
​
main();
​
function main() {
  usage();
  var techStack = process.argv[1];
  var gitHubName = process.argv[2];
  var destRepoMatch = getDestRepoUrl();
​
  clone(techStack, gitHubName, folder, destRepo[0], org);
}
​
function usage() {
  if (process.argv.length < 3) {
    console.log('usage: $0 techStack yourGithubName destRepoUrl');
    process.exit(-1);
  }
}
​
function getDestRepoUrl() {
  var repo = process.argv[3];
  var match = rxRepo.match(repo);
  if (!match) {
    console.log('Unable to parse destination repo URL: $destRepoUrl.');
    console.log('Make sure it has the form git@github.org:org/repo-name.git');
    process.exit(-2);
  }
  return match;
}
​
function clone(techStack, gitHubName, folder, destRepoUrl, org){
  // Clone the starter repo for the specified techstack and re-initialize it as
  // a new repo with correct remotes.
  var cwd = process.cwd();
  return git([
    'clone',
    'git@github.com/rangle/' + techStack,
    '--depth=1',
    '-o',
    gitHubName,
    folder
  ]).then(function () {
    process.chdir(path.join(cwd, folder));
    rimraf('.git');
    return git(['init'])
  }).then(function () {
    return gitRemoteAdd([
      'upstream',
      destRepoUrl
    ]);
  }).then(function () {
    return gitRemoteAdd([
      'origin',
      destRepoUrl + '/' + org + '/' + gitHubName
    ])
  });
}
​
function gitRemoteAdd(args) {
  if (!Array.isArray(args)) {
    args = [args];
  }
  return git(['remote', 'add'].concat(args));
}
​
function git(args) {
  return childProc('git', args);
}
​
function childProc(command, args) {
  var child = spawn(command, args);
​
  return new Promise((resolve, reject) => {
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
​
    child.stdout.on('data', function (data) { console.log(data); });
    child.stderr.on('data', function (data) { console.log(data); });
    child.stdout.on('close', function(code) {
      if (+code) {
        reject(new Error(command + ' exited with code ' + code));
      } else {
        resolve();
      }
    });
  }
}
```
