### ISSUE TITLE
Option to work without existing remote/Github repository

### ISSUE THREAD

**Issue by Meligy** [rangle/rangle-starter#35]
Can you please provide a way to get a project started without having to create a remote github repository first?

Good when all I want is play with the bits, explore the starters outputs, etc.

Thanks a lot.

**Comment by SethDavenport** [comment]
@Meligy you don't actually need to create a remote repo - this argument is simply to set up the git remotes for our internal style of working.

If you supply some fake arguments it will still clone the repo and let you run it locally, e.g:

``` sh
rangle-starter angular2-redux-starter Meligy git@github.org:fakeorg/fake.git
```

should work.

You can then clean up the remotes manually if you want since this is the only thing those arguments are used for anyway:

``` sh
git remote remove origin
git remote remove upstream
```

I'll consider adding this as a formal option though, thanks.

**Comment by SethDavenport** [comment]
Alternately you can clone the starter repos directly, without using the `rangle-starter` command:

``` sh
git clone git@github.com:rangle/angular-redux-starter
git clone git@github.com:rangle/angular2-redux-starter
git clone git@github.com:rangle/react-redux-starter
git clone git@github.com:rangle/typescript-react-redux-starter
```

**Comment by Meligy** [comment]
Thanks a lot :)

I thought from the webinars that I could clone these but when I went to them it seemed all info was about the CLI.

I'll have a play with that.

---

Now, regarding providing the fake git, it didn't work for me.

Here's the output:

```
~/Code/misc/rang  ᐅ rangle-starter angular2-redux-starter Meligy git@github.org:Meligy/rang.git        
Cloning into 'rang'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/usr/local/bin/rangle-starter: line 26: cd: rang: No such file or directory
Initialized empty Git repository in /Users/Meligy/Code/misc/rang/.git/
mv: rename package.json to package.json.bak: No such file or directory
cat: package.json.bak: No such file or directory
rm: package.json.bak: No such file or directory
mv: rename app.json to app.json.bak: No such file or directory
cat: app.json.bak: No such file or directory
rm: app.json.bak: No such file or directory
[master (root-commit) 29dc2c4] Initial commit from source:
 Committer: Meligy <Meligy@MeligyMBP.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 2 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 app.json
 create mode 100644 package.json
~/Code/misc/rang (master ✔) ᐅ ls
app.json     package.json

```

If relevant, I'm on latest Mac OS El Capitan, in a latest Oh My ZSH version terminal, with the following tooling versions:

Node: 5.5.0
NPM: 3.5.3
Git: 2.5.4

Thanks again.

**Comment by kosz** [comment]
would it make sense to not do any git init by default if no git url is provided ? 

personally I don't use rangle-starter because of the git things it does by default, I just clone the starter I want manually and `rm -rf .git`

**Comment by SethDavenport** [comment]
Yeah that makes sense - then we could make those params optional

**Comment by kosz** [comment]
So as this story has turned into something more like : 

`As a user I want the ability to use the rangle-starter without any parameters, and have a step by step process asking me questions.`

I now have a question :
