### ISSUE TITLE
Improve React stateless functional components

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#38]
There are a couple of improvements we can make to the way we use stateless functional components in the two React starters.

For example, consider this component: 

``` JavaScript
import React from 'react';

const Input = ({
  type,
  style,
  placeholder,
  fieldDefinition,
}) => (
  // ...
);

Input.propTypes = {
  type: React.PropTypes.string,
  style: React.PropTypes.object,
  placeholder: React.PropTypes.string,
  fieldDefinition: React.PropTypes.object.isRequired,
};

Input.defaultProps = {
  type: 'text',
  style: {},
  placeholder: '',
};

export default Input;
```

Now consider this version:

``` JavaScript
import React from 'react';

export default function Input({
  type = 'text',
  style = {},
  placeholder = '',
  fieldDefinition,
}) {
  return (
    // ...
  );
};

Input.propTypes = {
  type: React.PropTypes.string,
  style: React.PropTypes.object,
  placeholder: React.PropTypes.string,
  fieldDefinition: React.PropTypes.object.isRequired,
};
```

IMO it has several improvements:
1. less boilerplate
2. specifying default params inline as part of parameter destructuring is DRY-er
3. using named functions instead of arrow functions results in better stack traces (?). Since we don't need `this` in a stateless component there's no point to using an arrow function anyway.
4. we get to put the `export default` at the top; this reads more naturally to me.

**Comment by SethDavenport** [comment]
The typescript version is similar, but we trade propTypes for compile-time type checking:

``` typescript
import * as React from 'react';
​
interface IInputProps extends React.Props<any> {
  fieldDefinition: Object;
  type?: string;
  placeholder?: string;
  style?: Object;
};
​
export default function Input({
  type = 'text',
  style = {},
  placeholder = '',
  fieldDefinition,
}: IInputProps) {
  return (
    // ...
  );
}
```

**Comment by neilff** [comment]
For #2, one of the reasons we use `defaultProps` is to allow for parsing with react-docgen, with defaulting props via restructuring, will react-docgen still pick them up? Also, there might be a few strokes saved here, but how does it look with stateful components? There might be an odd disconnect if we have two different ways of declaring them based on which type of component is written.

Also, any idea if using named functions fixes the issue with `defaultName`? I know with the way we write components today, to have the component show up correctly named in the dev tools, you need to declare :

```
ComponentName.defaultName = 'ComponentName';
```

I believe this only applies to stateless components.

**Comment by SethDavenport** [comment]
named functions do appear to fix the defaultName issue.  I'll look into react docgen.

**Comment by SethDavenport** [comment]
It's not just about the keystrokes - the current approach isn't very DRY.
