### ISSUE TITLE
Support redux-devtools

### ISSUE THREAD

**Issue by cramhead** [rangle/rangle-starter#39]
There are dependencies for redux-devtools, but that they are not used.
Are you guys manually adding and removing redux-devtools?
I was thinking that it would be good if we could get them included via a specific `npm run *` command. Do you guys have a plan for this already in the works?

**Comment by SethDavenport** [comment]
Hmm might just be an oversight.  I'll look into it.

**Comment by cramhead** [comment]
Seems like the type definitions are a bit old for redux, so the approach specified in the redux-devtools repro with the third parameter passed to createStore, i.e. https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md, doesn't build with typescript.
I checked the definitely typed repro and there was a pull request, but the requester wanted to prefix interfaces with 'I' and it seems to just be sitting there. I'm pretty new to TypeScript so don't really have procedure for dealing with that. 
At present I'm splitting the configureStore into a configureStore.dev.ts and configureStore.prod.ts. as depicted in the linked walk through. 
Any thoughts?

**Comment by bennett000** [comment]
@cramhead there have been a number of issues with respect to Definitely Typed's Redux collection.  Fortunately Redux is going to have [official typings soon](https://github.com/reactjs/redux/pull/1413).  Once they get in, `tsc` should be able to find them using node module resolution. 

In the short term there are [Redux typings with generics](https://github.com/rangle/typings-redux) that are more accurate than Definitely Typed's but not quite as well done as [the official typings](https://github.com/reactjs/redux/pull/1413).  These can be installed with the [typings manager](https://www.npmjs.com/package/typings)

**Comment by SethDavenport** [comment]
@cramhead: alternatively, if you're not sold on typescript we maintain a very similar starter project based on babel which you may find to be a better fit for your needs:

https://github.com/rangle/react-redux-starter

The recent windows fixes have been ported over there as well.

**Comment by SethDavenport** [comment]
For the record, I've decided to go with the chrome extension version of redux devtools.  It's less intrusive to the code base and easier to use.  Working to update all starters with this in mind.

**Comment by SethDavenport** [comment]
The non-chrome-extension version of redux devtools also has a peer dependency on React, making it unsuitable for the Angular starters!  The Chrome Extension version has no such problem.

**Comment by SethDavenport** [comment]
Chrome extension redux devtools have been enabled on all starters.  You can get the extension here: https://github.com/zalmoxisus/redux-devtools-extension.

Tracking an issue with the angular starters where actions fired in-app are reflected in the tools, but actions fired from the tools are not reflected in the app.

Investigating...

**Comment by SethDavenport** [comment]
Actually it now works for angular 1.  The secret sauce is this: 

``` typescript
$ngRedux.subscribe(() => {
  setTimeout($rootScope.$apply, 0);
});
```

(source: https://github.com/wbuchwalter/ng-redux#using-devtools)

Hooking in the dev tools actions to the digest cycle, which makes sense.  There seems to be no analogous tip for ng2-redux.  I suspect something with zones is needed.  @e-schultz I'd like to get more insight from you next week.

**Comment by SethDavenport** [comment]
Analogously for ng2?

``` typescript
   ngOnInit() {
     this.disconnect = this.ngRedux.connect(
        this.mapStateToThis,
        this.mapDispatchToThis)(this);

     this.unsubscribe = this.ngRedux.subscribe(() => {
       this.applicationRef.tick();
     });
  }

  ngOnDestroy() {
    this.unsubscribe();
    this.disconnect();
  }
```
