### ISSUE TITLE
Decide, document, and test minimum browser support.

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#43]
I'm thinking we're limited by what the main frameworks support, but that we need to decide what we're willing to worry about as well.  I suggest the following:

es6-react, ts-react:
- IE9, Android 4.1, iOS 8

angular1:
- IE9, Android 4,1, iOS8

angular2:
- IE9, Android 4,1, iOS8? Depends on what ng2 supports in the end.

**Comment by SethDavenport** [comment]
@yuri @winkerVSbecks @e-schultz @neilff

**Comment by SethDavenport** [comment]
Added standard polyfills for es6 and es5.  The react app now at least runs on IE9 but anything that uses flexbox is borked.

This should get fixed when we include autoprefixer.

**Comment by bennett000** [comment]
Browser stats aren't necessarily reliable/consistent but it seems like there's still a fair bit of [IE8 Share](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0) out there.
