### ISSUE TITLE
Organize npm production vs devDependencies properly

### ISSUE THREAD

**Issue by JaKXz** [rangle/rangle-starter#44]
I noticed that the angular2 starter has _all_ its dependencies listed under `devDependencies`. This should probably get split properly for when someone has built an app and wants to deploy it and run `npm install --production` [in their `Dockerfile` for example].

**Comment by SethDavenport** [comment]
Webpack blurs the line between the two types of dependency, because these are no longer needed to _run_, they're needed to _build_.

So that's why everything is a devDep.  Sorting through which should be what is a philosophical thing right now.  Your argument about `npm install --production` is worth considering, however in order for it to work we'd have to list a bunch of build tools as prod dependencies (sass, webpack, typescript, etc.).

**Comment by SethDavenport** [comment]
@bertrandk @e-schultz @bennett000 @neilff thoughts?

**Comment by bennett000** [comment]
Whenever I make projects that produce a static build I treat the dependencies as development dependencies.  That's just what I've been doing though for pretty much the exact reasons Seth mentions, I'm not married to it, but it makes sense to me.

**Comment by e-schultz** [comment]
I've thought about this before - and have had projects where it's doing a build on the server it's deployed to (ie: heroku), and either end up telling Heroku to install dev dependencies anyway, or put everything under "dependencies". 

With the flow that most projects seem here to take of 'deploy to X / npm run build' - the line between dep and devDep does blur a little, as we are leaving it upto the server to also be responsible for building, which is a little iffy anyways.

**Comment by bennett000** [comment]
Having containers/servers do builds is a bit of a double edge sword.  

On the one hand it _guarantees_ that all dependencies are properly installed and compiled to the correct architecture with the correct case sensitivity.

On the other hand it means having a bunch of potentially dangerous build tools/steps left on the server/container.  

In a perfect world we might have some sort of build container and a deployment container, both made from the same source.  The build would have extra build deps on it, and produce to the deployment container.  Lots of moving parts though.
