### ISSUE TITLE
Evaluate GreenKeeper

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#45]
Automated npm dependency checks: http://greenkeeper.io/

Jason's looking into trying it out on the ng2 starter.

**Comment by JaKXz** [comment]
We've decided to enable Greenkeeper on all starters, and we'll continue to evaluate it. Marking this as done for now :)

**Comment by SethDavenport** [comment]
Hey @JaKXz did you do this for angula-redux-starter and typescript-react-redux-starter?

**Comment by SethDavenport** [comment]
Never mind I just did.

**Comment by SethDavenport** [comment]
Shiny and chrome for ever
