### ISSUE TITLE
Clean up how styles are used in all starters

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#49]
Currently there are a few things that could be improved about CSS for the react starters.
1. inline styles should use Radium so we can benefit from vendor prefixing etc.
2. we pass `className` around a lot when it should be part of the base styles for a component. 
3. [x] es6 react
4. [x] typescript react
5. [x] ng1
6. [x] ng2

**Comment by winkerVSbecks** [comment]
@SethDavenport How do you fee about getting rid of the `Column` component. IMO this doesn't provide much value. We could instead just do:

```
<div className="col ...">
    { children }
</div>
```

**Comment by SethDavenport** [comment]
Yeah I agree.  There are a few things like that...

**Comment by SethDavenport** [comment]
For reference, we decided not to go with Radium for now.  The reasoning is that 90% of your styling should be with basscss classes; anything exotic is best kept in a component-specific .css file that gets `required` into the JSX and uses BEM syntax for scoping.

This allows it to benefit from the entire postcss toolchain including theme variables and autoprefixer support (Radium does some prefixing but it's not as robust).

It's also an idiom that's preferred by our Design team.

If you have a need for heavy dynamic inline styles in your project, feel free to bring in Radium to your own repo after cloning the seed.

**Comment by SethDavenport** [comment]
Now that we have harmonized the apps across to the angular starters, they should get the new styles too.

**Comment by SethDavenport** [comment]
Both react projects are done.  Angular ones still TODO. I'll tackle them when I have time.

**Comment by winkerVSbecks** [comment]
This might be a reasonable alternative to Radium for React + TS inline style projects: https://github.com/postcss/autoprefixer#css-in-js

**Comment by SethDavenport** [comment]
That's cool, certainly an option.  I still think it's worth doing as much of the transforms at build time instead of at run time though.
