### ISSUE TITLE
add cssnano

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#55]
Minifies bundled styles using postcss

**Comment by SethDavenport** [comment]
At least for prodmode:

`npm install cssnano --save-dev`

webpack.config.js:

``` javascript
  // ...
  postcss: function() {
    return [
      require('postcss-import')({
        addDependencyTo: webpack
      }),
      require('postcss-cssnext'),
      require('autoprefixer', {
        browsers: ['ie >= 8', 'last 2 versions'],
      }),
      require('cssnano'), // Maybe only in prod mode?
    ];
  }
```

**Comment by jeremy8883** [comment]
Looking at the cssnano website, it looks like it will need to be:

```
require('cssnano')({ 'safe': true })
```

otherwise, the optimizations might be too aggressive.

**Comment by SethDavenport** [comment]
Sure, makes sense.

**Comment by BrendanFDMoore** [comment]
Jeremy, how far did you get in trying this out? Don't want to repeat work if it can be avoided.

**Comment by jeremy8883** [comment]
I had only run the line on my local instance of the react starter, just to test that the 'safe':true line works (it does). So feel free to take this task if you want.

**Comment by BrendanFDMoore** [comment]
Yea, I'm looking at this. @SethDavenport can you move to In Progress? (I don't have permission to change labels/status)

**Comment by SethDavenport** [comment]
@BrendanFDMoore : done. I also added you as a collaborator

**Comment by BrendanFDMoore** [comment]
PR created for `typescript-react-redux-starter`: https://github.com/rangle/typescript-react-redux-starter/pull/103

**Comment by BrendanFDMoore** [comment]
PR created for `react-redux-starter`: https://github.com/rangle/react-redux-starter/pull/148

**Comment by BrendanFDMoore** [comment]
PR created for `angular-redux-starter`: https://github.com/rangle/angular-redux-starter/pull/82

**Comment by BrendanFDMoore** [comment]
Oops, didn't post updates re waiting PRs.
`angular2-starter`: https://github.com/rangle/angular2-starter/pull/18
`angular2-redux-starter`: https://github.com/rangle/angular2-redux-starter/pull/117

**Comment by BrendanFDMoore** [comment]
This has been applied to all starters.
