### ISSUE TITLE
Update ng1 starter to use .component and component router

### ISSUE THREAD

**Issue by JaKXz** [rangle/rangle-starter#58]
https://docs.angularjs.org/guide/component

**Comment by SethDavenport** [comment]
Now that 1.5 is out that makes sense.

**Comment by mattmcfad** [comment]
We should also update ngcourse-next to reflect this: [Using Components in your Angular 1.x Application](http://ngcourse-1.rangle.io/handout/05-components/02_Components/11_Using_Components_in_your_Angular_1_x_Application.html)

@SethDavenport should this be included in #56 or in a separate ticket?

**Comment by SethDavenport** [comment]
@mattmcfad it's up to you.  You can roll it into #56 if you want.
