### ISSUE TITLE
angular-2 starter pack includes test files in dev + prod builds

### ISSUE THREAD

**Issue by nexus-uw** [rangle/rangle-starter#60]
currently the webpack config does not exclude `.test.ts` files.

**Comment by SethDavenport** [comment]
@nexus-uw Webpack only includes what's in the import tree from the entry file (app.ts).  So this shouldn't be an issue?

**Comment by nexus-uw** [comment]
while the test files are not included in the app.js, their transpliation errors do show up in the web console.

![screen shot 2016-03-16 at 6 36 42 pm](https://cloud.githubusercontent.com/assets/3188890/13831002/e4f51e2e-eba6-11e5-8381-939084073a13.png)

 not sure if this needs to (or can) be fixed at the end of the day.
