### ISSUE TITLE
Investigate postcss-local-scope

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#65]
Angular 2 scopes component-level styles by default (using ViewEncapsulation).  This is awesome because
1. our designers can have component-level css files, which is easier on them
2. no-one has to mess around with BEM syntax, which requires a lot of discipline
3. we still get first-class prefixing and browser targetting support via post-css/css-next/autoprefixer.

Most of this applies to React and Angular1, with the exception of scoping.

In those projects we scope using BEM syntax, which is verbose and fragile.  We could scope with inline styles and Radium, but then we have to make do with more limited/less flexible vendor prefixing.  It's also hard for our design team.

I want to look at https://www.npmjs.com/package/postcss-local-scope as a potential solution for ng1 and react.

**Comment by winkerVSbecks** [comment]
@SethDavenport does ng1 need an update too?

**Comment by SethDavenport** [comment]
Oh yeah I guess it does.

**Comment by SethDavenport** [comment]
Udpated the ng1 starter as well.

**Comment by BrendanFDMoore** [comment]
@winkerVSbecks Recently added `postcss-modules-local-by-default` to `angular-redux-starter`, `typescript-react-redux-starter` and `react-redux-starter`. It looks to me that this module does the same thing, and that we can close this card. 

https://github.com/css-modules/postcss-modules-local-by-default/blob/master/README.md
