### ISSUE TITLE
Ensure the ng2 starter conforms to our ng2 guidelines

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#68]
Ensure the ng2 starter conforms to our ng2 guidelines: 

http://blog.rangle.io/angular-2-style-guide/
https://github.com/rangle/angular2-guidelines

**Comment by SethDavenport** [comment]
Also worth noting that @bertrandk is working on our own internal style guide.  We should make sure the ng2 starter follows it.

**Comment by sumitarora** [comment]
@SethDavenport I can check both angular2-starter and angular2-redux-starter

**Comment by bertrandk** [comment]
@sumitarora Let me know if I can help.

**Comment by bennett000** [comment]
as of #152 we're trimming the starters down to "Hello World".  This card won't be relevant for them but it _is still relevant to the examples_.

**Comment by troyt-42** [comment]
@bennett000 Since our [style guide](https://github.com/rangle/angular2-guidelines) has not been updated from April, do we need to follow [Angular's style guide](https://angular.io/styleguide) for now?
