### ISSUE TITLE
Update React component tests to use Enzyme and Mocha

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/rangle-starter#72]

**Comment by SethDavenport** [comment]
Here's an example from Varun: https://github.com/winkerVSbecks/react-native-training/blob/07-ui-testing/test/Button.js

**Comment by SethDavenport** [comment]
@jeremy8883 is taking a stab at this.

**Comment by SethDavenport** [comment]
React starter done.  Typescript react starter pending.
