### ISSUE TITLE
[typescript-react-redux-starter] Only TS sourcemap of last edited file is kept in hot reloading (npm dev)

### ISSUE THREAD

**Issue by jumpinjackie** [rangle/rangle-starter#78]
When I run "npm dev" on the TS react starter, when I edit any TS or TSX file after running "npm dev" all the current TS sourcemaps are lost and only the sourcemap of the last edited TS/TSX file can be found in the Chrome devtools.

Is this normal behavior?

**Comment by SethDavenport** [comment]
@alexs is this what you were experiencing?

**Comment by SethDavenport** [comment]
Seems to be related to webpack hot loading.  If I turn it off, the problem goes away.

Since Angular 2 doesn't support hot loading the way react does I might as well just get rid of it from the Angular 2 starter.
