### ISSUE TITLE
Should we have an istanbul threshold set up by default?

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#8]

**Comment by JaKXz** [comment]
Related to rangle/react-redux-starter#184, and to a lesser extent rangle/angular2-redux-starter#162.

**Comment by clbond** [comment]
This has become possible on the karma-based starters now that the code coverage numbers are correct. The mocha-based starters still have incorrect configurations though. I think someone with more mocha experience might have better luck bringing those starters into line with the karma ones.

**Comment by SethDavenport** [comment]
We should do it, should just be args to istanbul

**Comment by SethDavenport** [comment]
api-koa-starter has it.

create-react-app - @danielfigueiredo does the generated project this have a CI coverage threshold set up?

angular2-starter does not have it
angular-redux-starter does not have it

**Comment by winkerVSbecks** [comment]
both angular2-starter & angular-redux-starter should have it now
