### ISSUE TITLE
Make angular2-starter more minimal

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#80]
This starter is for people who just want the toolchain, but aren't interested in our redux+atomic components approach.

We should replace the sample app there with something simpler and easier to maintain.

**Comment by sumitarora** [comment]
Pushed the changes: https://github.com/rangle/angular2-starter

**Comment by sumitarora** [comment]
@SethDavenport This is done

**Comment by SethDavenport** [comment]
Looks good @sumitarora, thanks.
