### ISSUE TITLE
angular2 starter pack no longer loads on IE11

### ISSUE THREAD

**Issue by nexus-uw** [rangle/rangle-starter#82]
I am seeing the following error  in the vendor.xxxxxx.js file when I load up the starter pack on IE11
![screen shot 2016-04-04 at 11 15 00 am](https://cloud.githubusercontent.com/assets/3188890/14252716/8aa9df90-fa56-11e5-966b-81ea841adb41.png)

mostly likely caused by new shims.xxxxxxxx.js build artifact being included after the vendor.xxxxxxxx.js file. 

![screen shot 2016-04-04 at 11 13 42 am](https://cloud.githubusercontent.com/assets/3188890/14252695/69ff8ea2-fa56-11e5-95d1-3a5241f70e64.png)

**Comment by SethDavenport** [comment]
Blerg.

I'll fix it soon, thanks @nexus-uw

**Comment by nexus-uw** [comment]
#IEIsTheNewIE
