### ISSUE TITLE
Enforce npm v3+ on starters

### ISSUE THREAD

**Issue by JaKXz** [rangle/rangle-starter#87]
Because of npm v2's weird `peerDependency` handling and the performance gains w/ npm 3.5+, I think it would be best to have the starters ship with support for npm 3 - 

Until such a time when Node 6 is LTS, and we don't have to worry about it, probably:

![node lts schedule](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)

**Comment by SethDavenport** [comment]
I disagree. LTS is what people should be using in prod.  Npm2 is what they get with it by default.  We need to make sure it works on vanilla LTS setups.
