### ISSUE TITLE
Evaluate ngrx vs. ng2-redux

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#89]
Can we make ng2-redux better? How do ngrx's devtools compare?

**Comment by sumitarora** [comment]
how are we making the comparison between the two?

**Comment by SethDavenport** [comment]
Mostly based on comparing the api and the dev tools.

Since we switched to the chrome extension dev tools I think redux has the edge because we no longer need to depend on react for them. Redux has a more mature middleware ecosystem as well.

As for API that's something we control now; looking forward to @e-schultz, @kosz and @bennett000's latest work in that area.

As long as there's a good ng2-redux story for connect() and for an rxjs-based selector mechanism, I'm inclined to favour redux to avoid further splitting the community between ng2 and react.

As the guy who maintains the starters I also have an ulterior motive in that my life is easier if our angular and react stacks have a consistent architecture.

That said, ngrx could still win out if:
- it explodes in popularity before we bring ng2-redux up to speed, or
- we run into intractable typings problems with redux.

Stay tuned - I hope to have more to report next week.

**Comment by SethDavenport** [comment]
With the release of n2-redux version 2.2.3 it's now a decent alternative again since it's brought observables to the table.  Sticking with it for now due to its better devtools support.

**Comment by smkamranqadri** [comment]
agree with as i am using ngrx in a project which dives me to learn and understand the api and ng2-redux similar to redux so i go for the ng2-redux.
