### ISSUE TITLE
[angular2-starter] Counter doesn't get initialized after navigating back

### ISSUE THREAD

**Issue by yleichanok** [rangle/rangle-starter#90]
And buttons loose their styles after navigating to another page and back. To reproduce:
1. Load the app
2. Click on 'About us'
3. Click on 'Counter' (or use browser's back button).
Though it starts working if you click once on any button. Tried it on latest Chrome and Firefox.

**Comment by SethDavenport** [comment]
@sumitarora can you take a look at this when you have a minute?

**Comment by SethDavenport** [comment]
Updating to Angular2 beta 17 appears to have fixed this.
