### ISSUE TITLE
[angular-redux-starter] Add sample unit test for a service

### ISSUE THREAD

**Issue by alber70g** [rangle/rangle-starter#91]
Is it possible to get an example for testing of a service with a $httpBackend? Or should I think about it in another way when using Redux?

**Comment by SethDavenport** [comment]
Hi @Alber70g

More comprehensive unit testing is on the roadmap for these starters.  In the meantime, you can get more information on testing services that make HTTP calls from our [blog post](http://blog.rangle.io/testing-your-angular-2-application-part2/) or from our [gitbook](http://ngcourse.rangle.io/handout/testing/services/http.html)

**Comment by SethDavenport** [comment]
Apologies - those are Angular 2 resources and I just noticed you're talking about the Angular 1 starter. Let me see if I can find some other resources for you.

**Comment by SethDavenport** [comment]
When testing angular1 services that use `$http` I have usually avoided the httpBackend stuff from angular-mocks in favour my own stubs with `sinon.spy` or `Jasmine.spyObject`.   I find it leads to cleaner, more decoupled unit tests.

With that in mind, testing a service that uses `$http` becomes the same as testing any other service.  For example, with `mocha` and `sinon`:

``` javascript

describe('myService', function () {
  var myService;
  var mockHttp;

  function initMocks($provide) {
     // Empty mock to start with; each test will supply the spies it needs.
     mockHttp = {};
     $provide.service('$http', function () {
       return $httpMock;
     });.
  }

  function initServiceUnderTest(_myService_) {
    myService = _myService_;
  }

  // Re-init everything before each tests to keep tests decoupled from each other.
  beforeEach(module('my-module.my-service'));
  beforeEach(module(initMocks));
  beforeEach(inject(initServiceUnderTests));

  it ('gets stuff from HTTP', function () {
    // Decide what the expected result from the mock should be for this test.
    var expectedHttpResponse = {
      status: 200,
      body: { stuff: '12345' }
    };

    // Initialize the mock with the minimum we need to verify this test case.
    // Using q instead of $q to avoid all the $rootScope.$apply nastiness angular
    // would otherwise bring into the tests. (GIVEN)
    httpMock.get = sinon.spy(function () { return q.when(expectedHttpResponse); });

    // Perform the test. Return the promise to mocha so it handles 'async-ness' properly.
    // (WHEN). Note that if we get a rejected promise, mocha will report it as an error.
    // Also note if our code tries to make unexpected HTTP requests, the mock will either
    // throw an error (e.g. post: undefined is not a function), or the .get.calledWith() 
    // expectation will fail.
    return myService.getStuff()
      .then(function (stuff) {
       // Do our verification (THEN).
       expect(stuff).to.eql('12345');
       expect(httpMock.get.calledOnce).to.be.true;
       expect(httpMock.get.calledWith('/stuff')).to.be.true;
     });
   });
});
```

The end result is  an overly-commented, but very clean, specific backend test that doesn't rely on any shared mock state.

**Comment by SethDavenport** [comment]
As for redux,  you may still have `$http` logic in services that needs to be tested.  The only change is that this code will be invoked from your action creators.

This in turn means that you may need to put your action creators in their own service so you can inject stuff into them using Angular's dependency injection.  So, something like:

``` javascript
angular.module('my-app.action-creators', [])
  .factory('actionService', function (myService) {

  return  {
    getStuffAction: getStuffAction,
    // ...
  };

  function getStuffAction() {
   return dispatch({
      types: [
         GET_STUFF_PENDING,
         GET_STUFF_SUCCESS,
         GET_STUFF_ERROR,
      ],
      payload: {
        promise: myService.getStuff()
      },
    });
  }
});
```

In this case, tests for `getStuffAction` would create `actionService` as the service under test, supply a minimal mock for 'myService', and a stub implementation for `dispatch`.

**Comment by alber70g** [comment]
Thanks a lot. But if I'm right, this is all javascript, and the angular-redux-starter is build with typescript. Is it possible that you add an example inside that project with the test.

**Comment by alber70g** [comment]
Hi @SethDavenport , I've tried to implement the unit test as described above, but I keep getting errors. It seems that webpack cannot resolve the module/service, even when included in the test.

It would be really nice to add a working unit test to the starter project (e.g. for filter or service). Would this be possible?

**Comment by SethDavenport** [comment]
@BrendanFDMoore has agreed to take a look at this.  We'll refactor our login action to use $http, hook it up to Redux, and then add a sample unit test.

**Comment by alber70g** [comment]
Thanks a lot! I'll be really helped with this addition

**Comment by BrendanFDMoore** [comment]
Hi @Alber70g - I've been working on this example and have a working build going in my `httptest` [branch](https://github.com/BrendanFDMoore/angular-redux-starter/tree/httptest). This will likely get merged into upstream master soon, but I wanted to give you a chance to take a look if you've been waiting.

Note that while an earlier commit was authenticating against `http://ngcourse.herokuapp.com/auth/login`, I had to change that to deal with breaking `e2e` tests. The heroku app is currently set to "authenticate" any request, regardless of credentials used, so the test confirming rejection of invalid credentials was breaking.

Now the auth is being handled by the local node server itself, and checking against a static `users.json` file. The client code is still making actual `$http` requests, though, and all the tests and mocks are valid as if this was hitting some remote server.

**Comment by alber70g** [comment]
Thanks a lot. I've been looking at your branch before :smile:. I see that you don't use the angular-service model? Is this intentionally because you're using Redux? I can see that I possibly want to create interceptors for certain things. I believe that would not be possible this way. Overall it looks nice. I'll try in the near future to implement it the same way in my own project. Thanks a lot!

**Comment by BrendanFDMoore** [comment]
If you're talking about using services for state management purposes, that's exactly right. We've found that `Redux` provides a better model for this that is less prone to problems. 

I've certainly used services for state in the past, and its probably fine for small/simple use cases, but it has a way of becoming less manageable with growth over time.

Certainly `ServerService` here (where the `$http` calls exist) is agnostic of any other services or even Redux. The actions and reducers come into play a layer above that, so you can use them with other models as well.

**Comment by BrendanFDMoore** [comment]
Auth has been updated to use [Passport](http://passportjs.org/docs) and tidied up. Now merged into `master` for `angular-redux-starter`.
