### ISSUE TITLE
Angular2 starter should use Jasmine, not mocha

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#93]
Since that's what the Angular2 team have settled on.

**Comment by sumitarora** [comment]
@SethDavenport done this for angular2-starter if all good I will do for redux one too. https://github.com/rangle/angular2-starter/pull/17

**Comment by kosz** [comment]
But why specifically is Jasmine the better option ? 
I doubt Jasmine has anything extra to offer to Redux. I'm sure there are some Angular 2 specific features, but with Redux a lot of those may not be needed ?

**Comment by SethDavenport** [comment]
We still want to test our Angular 2 components - that means using Angular2's modified version of Jasmine.

I'd rather not depend on two different testing frameworks if possible.
