### ISSUE TITLE
Add linting to config file(s)

### ISSUE THREAD

**Issue by BrendanFDMoore** [rangle/rangle-starter#95]
Linting is not currently enforce against `webpack.config.js` and any related files for loaders/plugings etc. We should probably add this.

**Comment by codebyuma** [comment]
Just wanted to confirm approach and requirements here. 

Four of the five starters use typescript but the config files and loaders are all javascript files. It doesn't look like ts-lint supports .js files yet (https://github.com/palantir/tslint/issues/515), so it looks like I'll have to add es-lint to cover these config files. @SethDavenport Does that sound reasonable? 

In terms of coverage, what should be linted? Should I assume all remaining .js files? A brief search across the starters shows that would include:
- webpack.config.js
- loaders.js
- karma.conf.js 
- e2e/*.js
- server/*.js
- shims/shims_for_IE.js

**Comment by SethDavenport** [comment]
Hi Uma,

Yes we'll need eslint and the standard .eslintrc for those: https://github.com/rangle/dev/tree/master/dotfiles

Basically everything except build output.

So:

`**/*.js`, but exclude `dist`

**Comment by BrendanFDMoore** [comment]
I would think it should be sufficient to include this in the `npm test`
sequence via the `npm run lint` chain (adding a third `lint-js` trigger)
and not worry about adding `eslint-loader` to the web pack sequence.

These are not build files themselves, so I'm not convinced it needs to run
on build. The CI failing via `npm test` should be enough, no?

**Comment by codebyuma** [comment]
@BrendanFDMoore the issue here is that the typescript linter won't run against javascript files, and since the build files are all javascript files we need to add eslint to handle that linting.

**Comment by codebyuma** [comment]
Just clarifying as we talked in person. No eslint-loader required, just es-lint :)

**Comment by codebyuma** [comment]
@SethDavenport quick question - the .eslintrc file in https://github.com/rangle/dev/tree/master/dotfiles doesn't include ES6-related rules. Should I use some of the ones in the react-redux-starter to keep them consistent? https://github.com/rangle/react-redux-starter/blob/master/.eslintrc

**Comment by SethDavenport** [comment]
Sure - that makes sense.

You can update the one in /dev too then :)

**Comment by codebyuma** [comment]
PRs are open for all the starters. I also added one for the /dev too - https://github.com/rangle/dev/pull/150
